# Generated by Django 6.0.4 on 2026-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
