# Generated by Django 6.0.4 on 2026-07-14 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('FACEBOOK_PAGE', 'Facebook Page'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP_BUSINESS', 'WhatsApp Business')], help_text='The platform being integrated (Facebook Page, Instagram, WhatsApp Business)', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Custom name or label for this connection (e.g. Page Name or Business Name)', max_length=255, null=True)),
                ('access_token', models.TextField(help_text='The API access token or system user token used to authenticate on behalf of the user')),
                ('platform_identifier', models.CharField(help_text='The external identifier on the platform (Facebook Page ID, Instagram Account ID, or Phone Number ID)', max_length=255)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional platform-specific metadata (e.g. WABA ID, Catalog ID, token expiry)')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the integration is active and should be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'integrations',
                'unique_together': {('user', 'platform', 'platform_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.CharField(help_text='Recipient identifier (phone number for WhatsApp, Page-Scoped ID for FB/Instagram)', max_length=255)),
                ('message_content', models.TextField(help_text='The payload/text content of the message sent')),
                ('platform_message_id', models.CharField(blank=True, help_text="The unique message ID returned by the platform's API", max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Details of the error if the sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'db_table': 'integration_message_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
