# Generated by Django 6.0.4 on 2026-07-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='The long-lived user access token for Facebook Graph API')),
                ('expires_at', models.DateTimeField(blank=True, help_text='The expiration time of the user access token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_user_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta User Token',
                'verbose_name_plural': 'Meta User Tokens',
                'db_table': 'meta_user_tokens',
            },
        ),
    ]
