# Generated by Django 6.0.4 on 2026-08-24 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_metausertoken'),
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created/connected this integration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('organization', 'platform', 'platform_identifier')},
        ),
    ]
