# Generated by Django 6.0.4 on 2026-08-24 13:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable AI auto-reply for this organization')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], default='openai', help_text='AI model provider (OpenAI, Google Gemini, Anthropic)', max_length=50)),
                ('model_name', models.CharField(blank=True, default='gpt-4o-mini', help_text='The specific model ID to use (e.g. gpt-4o-mini, gemini-1.5-flash, claude-3-haiku)', max_length=100)),
                ('api_key', models.TextField(blank=True, help_text='Custom API key if organization uses its own model credentials', null=True)),
                ('system_prompt', models.TextField(blank=True, default='You are a helpful, polite, and professional customer support assistant for our business. Reply concisely, clearly, and accurately to customer inquiries.', help_text='System prompt defining the persona, guidelines, and constraints for the AI agent')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal'), ('enthusiastic', 'Enthusiastic')], default='professional', help_text='General tone of voice for generated replies', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Controls reply creativity / randomness (0.0 = deterministic, 2.0 = highly creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum token limit for generated responses', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4096)])),
                ('fallback_message', models.TextField(blank=True, default='Thank you for contacting us! A member of our team will review your message and get back to you shortly.', help_text='Fallback message returned if AI response fails or confidence is low')),
                ('auto_reply_delay_seconds', models.IntegerField(default=0, help_text='Optional simulated delay before dispatching reply (in seconds)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('business_name', models.CharField(blank=True, help_text='Business or brand name for context in prompts', max_length=255, null=True)),
                ('business_description', models.TextField(blank=True, help_text='Summary of products, services, operating hours, and business details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(help_text='The organization this AI configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI Setting',
                'verbose_name_plural': 'AI Settings',
                'db_table': 'ai_settings',
            },
        ),
    ]
