# Generated by Django 6.0.4 on 2026-08-28 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('organizations', '0002_alter_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or name of the document', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional summary or description of the document', null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded document file (e.g. .txt, .md, .pdf, .csv, .json, .docx)', null=True, upload_to='knowledge_base/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, help_text='Extension or MIME type (e.g. txt, md, pdf, csv, json)', max_length=50, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('text', 'Raw Text'), ('faq', 'FAQ'), ('url', 'Web Page URL')], default='file', help_text='Source type: file, raw text, FAQ, or URL', max_length=50)),
                ('raw_content', models.TextField(blank=True, help_text='Extracted plain text content ready for indexing', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current indexing lifecycle status (pending, processing, indexed, failed)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if text extraction or indexing failed', null=True)),
                ('character_count', models.IntegerField(default=0, help_text='Character count of extracted content')),
                ('word_count', models.IntegerField(default=0, help_text='Word count of extracted content')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of vector chunks generated from this document')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of string tags for categorization and filtering')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom key-value metadata attributes for filtering')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this document is actively queried by the AI assistant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, help_text='Timestamp when vector indexing completed', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who uploaded or created this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this knowledge document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'db_table': 'knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(default=0, help_text='Sequence index of the chunk within the document')),
                ('content', models.TextField(help_text='The text snippet content of this chunk')),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count for the chunk content')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding numbers (float array)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Chunk-level metadata for context filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The parent document this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'knowledge_document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
