# Generated by Django 6.0.4 on 2026-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Default organization', help_text='Organization / Company name', max_length=255),
        ),
    ]
