# Generated by Django 6.0.4 on 2026-08-30 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_language',
            field=models.CharField(blank=True, default='English', help_text='Default communication language', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Brief summary/description of the organization', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo image', null=True, upload_to='organization_logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for URLs / identifiers', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, default='GMT+06:00', help_text='Organization timezone', max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(default='Starter Plan', help_text='Subscription plan tier name', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', max_length=50)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50)),
                ('max_messages', models.IntegerField(default=10000, help_text='Maximum allowed messages per cycle')),
                ('max_team_members', models.IntegerField(default=1, help_text='Maximum team members allowed')),
                ('max_connected_accounts', models.IntegerField(default=1, help_text='Maximum connected integration channels')),
                ('renews_at', models.DateTimeField(blank=True, help_text='Date when current billing cycle renews', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(help_text='Organization tied to this subscription plan', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
                'db_table': 'organization_subscriptions',
            },
        ),
    ]
